// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs8_ToiQC4e2ylJjAM6cWRLhCY4JyBMmk',
    appId: '1:209341589284:web:1eefc998a2a9c59758f5b1',
    messagingSenderId: '209341589284',
    projectId: 'screenique-17e32',
    authDomain: 'screenique-17e32.firebaseapp.com',
    storageBucket: 'screenique-17e32.firebasestorage.app',
    measurementId: 'G-J42H98HGH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4szppCXYxyEGdUndT7jjTBBDr0FZjaew',
    appId: '1:209341589284:android:8ad9b1b7cd7ad34158f5b1',
    messagingSenderId: '209341589284',
    projectId: 'screenique-17e32',
    storageBucket: 'screenique-17e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChwYPSdKsHka0ulqddRs7pymU06MUUYP0',
    appId: '1:209341589284:ios:ad3a529c3e63f35058f5b1',
    messagingSenderId: '209341589284',
    projectId: 'screenique-17e32',
    storageBucket: 'screenique-17e32.firebasestorage.app',
    iosClientId: '209341589284-et2al2mi0dv7q2cmm2mt2bejjq1g8iav.apps.googleusercontent.com',
    iosBundleId: 'com.example.screenique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChwYPSdKsHka0ulqddRs7pymU06MUUYP0',
    appId: '1:209341589284:ios:ad3a529c3e63f35058f5b1',
    messagingSenderId: '209341589284',
    projectId: 'screenique-17e32',
    storageBucket: 'screenique-17e32.firebasestorage.app',
    iosClientId: '209341589284-et2al2mi0dv7q2cmm2mt2bejjq1g8iav.apps.googleusercontent.com',
    iosBundleId: 'com.example.screenique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs8_ToiQC4e2ylJjAM6cWRLhCY4JyBMmk',
    appId: '1:209341589284:web:c5315bce472e4a7658f5b1',
    messagingSenderId: '209341589284',
    projectId: 'screenique-17e32',
    authDomain: 'screenique-17e32.firebaseapp.com',
    storageBucket: 'screenique-17e32.firebasestorage.app',
    measurementId: 'G-K99NW9B3W9',
  );
}
